# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Home
email: vibhorag24@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://vibhoraggarwal.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  vibhoraggarwal

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-tidy
  - jekyll-jupyter-notebook

include:
  - '_pages'

# jekyll-tidy configuration
jekyll_tidy:
  compress_html: false

# jekyll-assets configuration
assets:
  compress:
    js: true
    css: true
  prefix: /assets
  features:
    liquid: true
  assets:
    - "bootstrap.js"
    - "popper.js"
    - "blog.scss"
    - "main.scss"
  digest: true
  sources:
    - _assets/css
    - _assets/scss
    - _assets/images
    - _vendor/bundle/ruby/2.3.0/gems/bootstrap-4.0.0.beta/assets/javascripts/
    - _vendor/bundle/ruby/2.3.0/gems/popper_js-1.11.1/assets/javascripts/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
